/* AUTO-GENERATED by scripts/build_posts.py — do not edit.
   Add or edit posts in content/posts/*.md instead. */

const POSTS = [
  {
    "title": "Fundamentals of Artificial Intelligence (IN2406) — Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Algorithms/Fundamentals of Artificial Intelligence (IN2406)"
    ],
    "tags": [
      "algorithms",
      "search",
      "planning",
      "constraint satisfaction",
      "TUM"
    ],
    "url": "posts/foAI.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for Fundamentals of Artificial Intelligence (IN2406) at TUM — rational agents, search, constraint satisfaction, logic, planning, and probabilistic reasoning."
  },
  {
    "title": "GAMES204 — Computational Imaging: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computational Imaging and Display/Computational Imaging/GameS204"
    ],
    "tags": [
      "Computer Graphics",
      "computational imaging",
      "GAMES204"
    ],
    "url": "posts/games204.html",
    "updated": "2026-09-03",
    "mtime": "2026-09-03T22:41:27+02:00",
    "words": 3281,
    "minutes": 12,
    "summary": "Notes for GAMES204 (Computational Imaging)."
  },
  {
    "title": "GAMES103 — Physically-Based Animation Note1: Intro and Math Basics",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Animation/Games103"
    ],
    "tags": [
      "Computer Graphics",
      "physics simulation",
      "GAMES103"
    ],
    "url": "posts/games103-note1.html",
    "updated": "2026-08-25",
    "mtime": "2026-08-25T10:24:57+02:00",
    "words": 856,
    "minutes": 3,
    "summary": "GAMES103 note 1 — what physics-based animation is, the graphics pipeline, and the math toolbox of vectors, matrices and calculus for simulation."
  },
  {
    "title": "GAMES103 — Physically-Based Animation Note2: Rigid Body Dynamics and Contacts",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Animation/Games103"
    ],
    "tags": [
      "Computer Graphics",
      "physics simulation",
      "GAMES103"
    ],
    "url": "posts/games103-note2.html",
    "updated": "2026-09-03",
    "mtime": "2026-09-03T22:41:27+02:00",
    "words": 8724,
    "minutes": 34,
    "summary": "GAMES103 note 2 — rigid body dynamics — state integration, rotation representations, and contact handling."
  },
  {
    "title": "GAMES103 — Physically-Based Animation Note3: Cloth",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Animation/Games103"
    ],
    "tags": [
      "Computer Graphics",
      "physics simulation",
      "GAMES103"
    ],
    "url": "posts/games103-note3.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 60,
    "minutes": 1,
    "summary": "GAMES103 note 3 — cloth simulation — mass-spring systems, implicit integration, and strain limiting."
  },
  {
    "title": "GAMES103 — Physically-Based Animation Note4: Linear Finite Element Method",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Animation/Games103"
    ],
    "tags": [
      "Computer Graphics",
      "physics simulation",
      "GAMES103"
    ],
    "url": "posts/games103-note4.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 38,
    "minutes": 1,
    "summary": "GAMES103 note 4 — the linear finite element method for elastic solids."
  },
  {
    "title": "GAMES103 — Physically-Based Animation Note5: Fluid",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Animation/Games103"
    ],
    "tags": [
      "Computer Graphics",
      "physics simulation",
      "GAMES103"
    ],
    "url": "posts/games103-note5.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 45,
    "minutes": 1,
    "summary": "GAMES103 note 5 — fluid simulation — height fields, Eulerian grids, and SPH."
  },
  {
    "title": "GAMES105 — Computer Character Animation: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Animation/Games105"
    ],
    "tags": [
      "Computer Graphics",
      "character animation",
      "kinematics",
      "GAMES105"
    ],
    "url": "posts/games105.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for GAMES105 (Fundamentals of Computer Character Animation) — forward/inverse kinematics, motion capture data, and physics-based character control."
  },
  {
    "title": "GAMES102 — Geometric Modeling and Processing: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Geometry/Games102"
    ],
    "tags": [
      "Computer Graphics",
      "geometry processing",
      "GAMES102"
    ],
    "url": "posts/games102.html",
    "updated": "2026-08-29",
    "mtime": "2026-08-29T13:08:59+02:00",
    "words": 69,
    "minutes": 1,
    "summary": "Notes for GAMES102 (Geometric Modeling and Processing)."
  },
  {
    "title": "GAMES301 — Surface Parameterization: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Geometry/Games301"
    ],
    "tags": [
      "Computer Graphics",
      "geometry processing",
      "GAMES301"
    ],
    "url": "posts/games301.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for GAMES301 (Surface Parameterization)."
  },
  {
    "title": "GAMES302 — Isogeometric Analysis: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Geometry/Games302"
    ],
    "tags": [
      "Computer Graphics",
      "isogeometric analysis",
      "splines",
      "GAMES302"
    ],
    "url": "posts/games302.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for GAMES302 (Isogeometric Analysis) — splines and NURBS as a unified representation for geometric modeling and numerical simulation."
  },
  {
    "title": "GAMES101 — Modern Computer Graphics: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Rendering/Games101"
    ],
    "tags": [
      "Computer Graphics",
      "rendering",
      "GAMES101"
    ],
    "url": "posts/games101.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for GAMES101 (Introduction to Modern Computer Graphics) — transformations, rasterization, shading, geometry, ray tracing, and animation."
  },
  {
    "title": "GAMES202 — Real-Time High Quality Rendering: Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Graphics/Rendering/Games202"
    ],
    "tags": [
      "Computer Graphics",
      "real-time rendering",
      "GAMES202"
    ],
    "url": "posts/games202.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for GAMES202 (Real-Time High Quality Rendering) — shadows, environment lighting, global illumination, and real-time ray tracing."
  },
  {
    "title": "3D Computer Vision (IN2228) — Notes 1",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Computer Vision/3D Computer Vision (IN2228)"
    ],
    "tags": [
      "Computer Vision",
      "multiple view geometry",
      "SLAM",
      "3D reconstruction",
      "TUM"
    ],
    "url": "posts/3dcv-note1.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T19:07:37+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for 3D Computer Vision (IN2228, formerly Computer Vision II — Multiple View Geometry) at TUM — camera models, epipolar geometry, two-view reconstruction, bundle adjustment, and visual SLAM."
  },
  {
    "title": "Machine Learning (IN2064) — Notes",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Machine Learning/Machine Learning (IN2064)"
    ],
    "tags": [
      "machine learning",
      "probabilistic models",
      "optimization",
      "TUM"
    ],
    "url": "posts/machine-learning.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for Machine Learning (IN2064) at TUM — regression, classification, probabilistic models, optimization, kernels, and deep learning basics."
  },
  {
    "title": "Robotics (IN2067) — Notes 1",
    "date": "2026-08-24",
    "categories": [
      "Course notes/Robotics/Robotics (IN2067)"
    ],
    "tags": [
      "robotics",
      "kinematics",
      "dynamics",
      "control",
      "TUM"
    ],
    "url": "posts/robotics.html",
    "updated": "2026-08-24",
    "mtime": "2026-08-24T16:39:11+02:00",
    "words": 3,
    "minutes": 1,
    "summary": "Notes for Robotics (IN2067) at TUM — spatial descriptions, forward and inverse kinematics, dynamics, trajectory generation, and control."
  },
  {
    "title": "Computer Vision III (IN2375) — Notes 3: Image Segmentation",
    "date": "2026-08-23",
    "categories": [
      "Course notes/Computer Vision/Computer Vision III (IN2375)"
    ],
    "tags": [
      "Deep learning",
      "Computer Vision",
      "TUM",
      "segmentation",
      "video object segmentation"
    ],
    "url": "posts/cv3-image-segmentation.html",
    "updated": "2026-09-03",
    "mtime": "2026-09-03T22:41:27+02:00",
    "words": 11047,
    "minutes": 44,
    "summary": "Third notes for CV3 (IN2375, Detection, Segmentation and Tracking) at TUM — segmentation from superpixels, clustering and normalized cuts through CRFs to FCNs, instance segmentation with Mask R-CNN and PointRend, panoptic segmentation and its evaluation, and video object segmentation from optical flow to pixel-wise retrieval."
  },
  {
    "title": "Computer Vision III (IN2375) — Notes 4: Modern Approaches",
    "date": "2026-08-23",
    "categories": [
      "Course notes/Computer Vision/Computer Vision III (IN2375)"
    ],
    "tags": [
      "Deep learning",
      "Computer Vision",
      "TUM",
      "transformers",
      "self-supervised learning",
      "semi-supervised learning"
    ],
    "url": "posts/cv3-modern-approaches.html",
    "updated": "2026-08-27",
    "mtime": "2026-08-27T10:42:10+02:00",
    "words": 15949,
    "minutes": 56,
    "summary": "Fourth notes for CV3 (IN2375, Detection, Segmentation and Tracking) at TUM — transformers from attention to ViT, Swin, DETR and Mask2Former; self-supervised learning from pretext tasks through contrastive (SimCLR, MoCo) and non-contrastive methods (DINO, MAE) with their downstream applications; and semi-supervised learning from its core assumptions to self-training, SAM, and consistency regularisation."
  },
  {
    "title": "Computer Vision III (IN2375) — Notes 2: Object Tracking",
    "date": "2026-08-23",
    "categories": [
      "Course notes/Computer Vision/Computer Vision III (IN2375)"
    ],
    "tags": [
      "Deep learning",
      "Computer Vision",
      "TUM",
      "object tracking",
      "MOT"
    ],
    "url": "posts/cv3-object-tracking.html",
    "updated": "2026-08-29",
    "mtime": "2026-08-29T21:19:52+02:00",
    "words": 6965,
    "minutes": 27,
    "summary": "Second notes for CV3 (IN2375, Detection, Segmentation and Tracking) at TUM — object tracking from Bayesian filtering to single-object online trackers (GOTURN, MDNet), multi-object association via motion models, Tracktor and ReID, graph-based MOT with message passing networks, and how tracking is evaluated."
  },
  {
    "title": "Computer Vision III (IN2375) — Notes 1: Object Detection",
    "date": "2026-08-20",
    "categories": [
      "Course notes/Computer Vision/Computer Vision III (IN2375)"
    ],
    "tags": [
      "Deep learning",
      "Computer Vision",
      "TUM",
      "object detection"
    ],
    "url": "posts/cv3-object-detection.html",
    "updated": "2026-08-29",
    "mtime": "2026-08-29T13:08:59+02:00",
    "words": 8176,
    "minutes": 29,
    "summary": "First notes for CV3 (IN2375, Detection, Segmentation and Tracking) at TUM — object detection from classical single-stage pipelines to the R-CNN family and modern one-stage detectors, plus how detection is evaluated."
  }
];
