#!/usr/bin/env python3
"""Generate posts/*.html and posts.js from content/posts/*.md.

Each Markdown source starts with YAML front matter:

    ---
    title: My Post
    date: 2026-09-01
    categories: [Course notes, Vision]   # or a single one:  category: Course notes
    tags: [slam, 3d vision]
    summary: One or two lines shown in the blog index.
    ---
    Body in Markdown...

Run locally with:  python3 scripts/build_posts.py
CI runs it automatically on every push that touches content/.
"""

import html
import json
import math
import re
import subprocess
import sys
from datetime import date as _date
from datetime import datetime
from pathlib import Path

import markdown
import yaml

ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = ROOT / "content" / "posts"
OUT_DIR = ROOT / "posts"
POSTS_JS = ROOT / "posts.js"

MARKER = "<!-- generated by scripts/build_posts.py — edit content/posts/*.md instead -->"

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {marker}
    <title>{title_esc} — Rui Ying</title>
    <link href="https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,300;0,8..60,400;0,8..60,600;1,8..60,400&family=Source+Sans+3:wght@300;400;600&family=Noto+Serif+SC:wght@400;600&family=Noto+Sans+SC:wght@400;500&family=JetBrains+Mono:wght@400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="../style.css">
    <script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
</head>
<body>

    <nav class="topnav">
        <div class="topnav-inner">
            <ul class="topnav-links">
                <li><a href="../index.html#about">About me</a></li>
                <li><a href="../index.html#news">News</a></li>
                <li><a href="../index.html#publications">Publications</a></li>
                <li><a class="active" href="../blog.html">Blog</a></li>
            </ul>
        </div>
    </nav>

    <div class="page-wrapper narrow{toc_class}">{toc_html}
        <main class="main-content post-page">

            <a class="back-link" href="../blog.html">&larr; Back to blog</a>

            <h1>{title_esc}</h1>
            <div class="post-meta">
                <span>Published {date_human}</span>{updated_html} ·
                {categories_html} ·
                <span>{words:,} words · {minutes} min read</span><span id="busuanzi_container_page_pv" style="display:none"> ·
                <span id="busuanzi_value_page_pv"></span> views</span>
            </div>

{body}

        </main>

        <footer class="page-footer">
            &copy; 2026 Rui Ying &middot; Munich, Germany
        </footer>
    </div>

    <script async src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
<!--SCROLLSPY-->
</body>
</html>
"""

FRONT_MATTER_RE = re.compile(r"\A---\s*\n(.*?)\n---\s*\n?(.*)\Z", re.S)


def fail(msg):
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


def parse_source(path):
    text = path.read_text(encoding="utf-8")
    m = FRONT_MATTER_RE.match(text)
    if not m:
        fail(f"{path.name}: missing '---' front matter block at the top")
    try:
        meta = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError as e:
        fail(f"{path.name}: bad front matter: {e}")
    if not isinstance(meta, dict):
        fail(f"{path.name}: front matter must be key: value lines")

    for key in ("title", "date"):
        if not meta.get(key):
            fail(f"{path.name}: front matter is missing '{key}'")

    cats = meta.get("categories") or meta.get("category") or []
    if isinstance(cats, str):
        cats = [c.strip() for c in cats.split(",") if c.strip()]
    cats = [str(c) for c in cats]
    if not cats:
        fail(f"{path.name}: front matter needs 'category' or 'categories'")

    d = meta["date"]
    if isinstance(d, datetime):
        d = d.date()
    if isinstance(d, _date):
        iso = d.isoformat()
    else:
        iso = str(d).strip()
        try:
            datetime.strptime(iso, "%Y-%m-%d")
        except ValueError:
            fail(f"{path.name}: date must be YYYY-MM-DD, got {iso!r}")

    tags = meta.get("tags") or []
    if isinstance(tags, str):
        tags = [t.strip() for t in tags.split(",") if t.strip()]
    tags = [str(t) for t in tags]

    return {
        "slug": path.stem,
        "path": path,
        "meta": meta,
        "title": str(meta["title"]),
        "date": iso,
        "categories": cats,
        "tags": tags,
        "summary": str(meta.get("summary") or "").strip(),
        "body_md": m.group(2),
    }


HEADING_RE = re.compile(r'<h([23]) id="([^"]+)">(.*?)</h\1>', re.S)

SCROLLSPY_JS = """    <script>
    (function () {
        var links = document.querySelectorAll(".post-toc a");
        if (!links.length) { return; }
        var map = {};
        var heads = [];
        links.forEach = Array.prototype.forEach;
        links.forEach.call(links, function (a) {
            var id = decodeURIComponent(a.getAttribute("href").slice(1));
            var h = document.getElementById(id);
            if (h) { map[id] = a; heads.push(h); }
        });
        function activate(id) {
            for (var k in map) { map[k].classList.toggle("active", k === id); }
        }
        var obs = new IntersectionObserver(function (entries) {
            var visible = entries.filter(function (e) { return e.isIntersecting; });
            if (visible.length) {
                activate(visible[0].target.id);
            }
        }, { rootMargin: "0px 0px -70% 0px", threshold: 0 });
        heads.forEach(function (h) { obs.observe(h); });
    })();
    </script>"""


def build_toc(body_html):
    """Sidebar bookmark list from the post's numbered h2/h3 headings."""
    items = []
    for level, hid, text in HEADING_RE.findall(body_html):
        label = html.unescape(re.sub(r"<[^>]+>", "", text)).strip()
        items.append((level, hid, label))
    if len(items) < 3:
        return "", ""
    lis = "\n".join(
        f'                <li class="toc-h{level}"><a href="#{hid}">{html.escape(label)}</a></li>'
        for level, hid, label in items
    )
    toc = f"""
        <aside class="post-toc">
            <div class="post-toc-title">Contents</div>
            <ul>
{lis}
            </ul>
        </aside>"""
    return " with-toc", toc


CJK_RE = re.compile(r"[\u3040-\u30ff\u3400-\u4dbf\u4e00-\u9fff\uf900-\ufaff]")
LATIN_WORD_RE = re.compile(r"[A-Za-z0-9]+(?:['\u2019-][A-Za-z0-9]+)*")


def count_words(body_html):
    """CJK characters count as one word each; latin words by whitespace."""
    text = re.sub(r"<[^>]+>", " ", body_html)
    text = html.unescape(text)
    cjk = len(CJK_RE.findall(text))
    latin = len(LATIN_WORD_RE.findall(text))
    # ~350 CJK chars/min, ~200 latin words/min
    minutes = max(1, math.ceil(cjk / 350 + latin / 200))
    return cjk + latin, minutes


def updated_date(path, meta, published_iso):
    """Explicit 'updated' front matter wins; else the file's last git commit."""
    u = meta.get("updated")
    if u:
        if hasattr(u, "isoformat"):
            return u.isoformat()[:10]
        return str(u).strip()
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%as", "--", str(path)],
            capture_output=True, text=True, cwd=ROOT, timeout=10,
        )
        got = out.stdout.strip()
        if got:
            return got
    except Exception:
        pass
    return published_iso


def render_body(md_text):
    body = markdown.markdown(
        md_text,
        extensions=["extra", "sane_lists", "toc", "pymdownx.arithmatex"],
        extension_configs={"pymdownx.arithmatex": {"generic": True}},
        output_format="html5",
    )
    # Site-absolute image/file paths work when deployed but not when the file
    # is opened locally; rewrite them relative to the posts/ directory.
    body = body.replace('src="/images/', 'src="../images/')
    body = body.replace('href="/images/', 'href="../images/')

    # A paragraph that is just an image becomes a <figure>, with the
    # Markdown alt text as its caption.
    def to_figure(m):
        img = m.group(1)
        alt = re.search(r'alt="([^"]*)"', img)
        caption = f"<figcaption>{alt.group(1)}</figcaption>" if alt and alt.group(1) else ""
        return f"<figure>{img}{caption}</figure>"

    body = re.sub(r"<p>(<img [^>]*>)</p>", to_figure, body)
    return body


def build():
    if not SRC_DIR.is_dir():
        fail(f"source directory {SRC_DIR} does not exist")
    OUT_DIR.mkdir(exist_ok=True)

    posts = []
    for path in sorted(SRC_DIR.glob("*.md")):
        if path.stem.startswith("_") or path.name.lower() == "readme.md":
            continue
        post = parse_source(path)
        date_human = datetime.strptime(post["date"], "%Y-%m-%d").strftime("%-d %B %Y")
        body = render_body(post["body_md"])
        toc_class, toc_html = build_toc(body)
        post["words"], post["minutes"] = count_words(body)
        post["updated"] = updated_date(path, post["meta"], post["date"])
        updated_html = ""
        if post["updated"] > post["date"]:
            upd_human = datetime.strptime(post["updated"], "%Y-%m-%d").strftime("%-d %B %Y")
            updated_html = f" ·\n                <span>Updated {upd_human}</span>"
        page = PAGE_TEMPLATE.format(
            marker=MARKER,
            title_esc=html.escape(post["title"]),
            categories_html=" · ".join(
                f'<span class="post-category">{html.escape(c)}</span>'
                for c in post["categories"]
            ),
            date_human=date_human,
            updated_html=updated_html,
            words=post["words"],
            minutes=post["minutes"],
            toc_class=toc_class,
            toc_html=toc_html,
            body=body,
        )
        page = page.replace("<!--SCROLLSPY-->", SCROLLSPY_JS if toc_html else "")
        out = OUT_DIR / f"{post['slug']}.html"
        out.write_text(page, encoding="utf-8")
        posts.append(post)
        print(f"built  posts/{out.name}")

    # Remove generated pages whose Markdown source is gone. Hand-written
    # HTML files (no marker) are never touched.
    live_slugs = {p["slug"] for p in posts}
    for old in OUT_DIR.glob("*.html"):
        if old.stem in live_slugs:
            continue
        if MARKER in old.read_text(encoding="utf-8"):
            old.unlink()
            print(f"removed posts/{old.name} (source deleted)")

    posts.sort(key=lambda p: p["date"], reverse=True)
    entries = [
        {
            "title": p["title"],
            "date": p["date"],
            "categories": p["categories"],
            "tags": p["tags"],
            "url": f"posts/{p['slug']}.html",
            "updated": p["updated"],
            "words": p["words"],
            "minutes": p["minutes"],
            "summary": p["summary"],
        }
        for p in posts
    ]
    js = (
        "/* AUTO-GENERATED by scripts/build_posts.py — do not edit.\n"
        "   Add or edit posts in content/posts/*.md instead. */\n\n"
        "const POSTS = " + json.dumps(entries, indent=2, ensure_ascii=False) + ";\n"
    )
    POSTS_JS.write_text(js, encoding="utf-8")
    print(f"wrote  posts.js ({len(entries)} posts)")


if __name__ == "__main__":
    build()
